import { MetricCard } from '../components/MetricCard'
import type { DemoState } from '../domain/types'
import '../styles/print.css'

export function ImpactScreen({ state, navigate }: { state: DemoState; navigate: (path: string) => void }) {
  const verified = state.verifications.flatMap(verification => {
    const barrier = state.barriers.find(item => item.id === verification.barrierId && item.status === 'verified')
    const workOrder = state.workOrders.find(item => item.id === verification.workOrderId && item.barrierId === barrier?.id)
    return verification.decision === 'accepted' && barrier && workOrder?.repairEvidence.length ? [{ verification, barrier, workOrder }] : []
  })
  return <div className="screen-stack impact-report"><section className="hero-panel"><p className="eyebrow">Evidence-chain impact report · illustrative demo data</p><h1>Bounded verified outcomes</h1><p>Only repairs with repair evidence and an accepted independent journey retest are included.</p><button className="button-primary no-print" onClick={() => window.print()}>Print evidence summary</button></section><section className="metric-grid"><MetricCard label="Verified repairs" value={verified.length} detail="Accepted for defined journeys and recorded conditions."/><MetricCard label="Successful journey tests" value={verified.length} detail="One bounded successful retest per included repair."/><MetricCard label="Pilot spend" value={verified.length ? '₹17,500' : 'Not available'} detail="Estimated midpoint; meaningful only for this fictional case."/></section><section><h2>Traceable outcomes</h2>{verified.length === 0 ? <p>No accepted verified repairs yet. Awaiting-verification and rework records are excluded.</p> : verified.map(({ barrier, workOrder, verification }) => <article className="trace-record" key={verification.id}><div><p className="eyebrow">Verified repair for this journey and test conditions</p><h3>{barrier.title}</h3><p>{verification.definedTestConditions}</p></div><dl><div><dt>Barrier</dt><dd><a href={`/barriers/${barrier.id}`} onClick={event => { event.preventDefault(); navigate(`/barriers/${barrier.id}`) }}>{barrier.id}</a></dd></div><div><dt>Work order</dt><dd><a href={`/work-orders/${barrier.id}`} onClick={event => { event.preventDefault(); navigate(`/work-orders/${barrier.id}`) }}>{workOrder.id}</a></dd></div><div><dt>Repair evidence</dt><dd>{workOrder.repairEvidence.map(item => item.id).join(', ')}</dd></div><div><dt>Verification</dt><dd>{verification.id}</dd></div><div><dt>Timeline event</dt><dd>{state.activity.find(item => item.barrierId === barrier.id && item.toStatus === 'verified')?.id ?? 'Accepted retest record'}</dd></div></dl></article>)}</section><footer className="print-disclaimer"><strong>Illustrative demo data.</strong> A bounded retest reports one defined journey, access requirement and set of test conditions. It is not universal usability, professional certification or a determination of legal compliance.</footer></div>
}
